// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WestWindSystem.Entities
{
    public partial class Territory
    {
        private string _TerritoryDescription;
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        
        [StringLength(20, MinimumLength = 1, ErrorMessage = "Territory Id is limit to 20 characters")]
        public string TerritoryId { get; set; }
        [Required]
        [StringLength(50)]
        //[Required(ErrorMessage = "Territory Desccription is required")]
        //[StringLength(50, MinimumLength = 1, ErrorMessage = "Territory Description is limit to 50 characters")]
        public string TerritoryDescription
        {
            get 
            {
                //return _TerritoryDescription.Trim();
                return _TerritoryDescription != null ? _TerritoryDescription.Trim() : null;
            }
            set 
            {
                _TerritoryDescription = value;
            }
        }
        [Column("RegionID")]
        public int RegionId { get; set; }

        [ForeignKey(nameof(RegionId))]
        [InverseProperty("Territories")]

        // this is a virtual mapping of the relationship between this file
        //and another file
        //Territories on the database is realted to the Regions
        //this virtual property is indicating that any
        //particular record in Territories is relatred to
        //a particular record in  Region
        public virtual Region Region { get; set; }
    }
}