// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WestWindSystem.Entities
{
    public partial class Territory
    {
        [Key]
        [Column("TerritoryID")]
        [StringLength(20)]
        public string TerritoryId { get; set; }
        [Required]
        [StringLength(50)]
        public string TerritoryDescription { get; set; }
        [Column("RegionID")]
        public int RegionId { get; set; }

        [ForeignKey(nameof(RegionId))]
        [InverseProperty("Territories")]

        // this is a virtual mapping of the relationship between this file
        //and another file
        //Territories on the database is realted to the Regions
        //this virtual property is indicating that any
        //particular record in Territories is relatred to
        //a particular record in  Region
        public virtual Region Region { get; set; }
    }
}